services:
  - type: web
    name: bot-lobo-cripto
    env: node
    runtime: node
    plan: starter
    buildCommand: npm ci --only=production && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    healthCheckPath: /api/status
    autoDeploy: true
    region: oregon